### ISSUE TITLE
Returned typed array

### ISSUE THREAD

**Issue by NicolasRannou** [OHIF/image-JPEG2000#6]
Hi, I would like some clarification about the documentation:
In the readme, it states that jpxData is uint8 and returns pixelData as int16.

Is it always the case? or somehow it could sometimers return uint8, int8, uint16 and int16?

Thanks!

```
jpxImage.parse(jpxData);
var width = jpxImage.width;
var height = jpxImage.height;
var pixelData = tileComponents.items;
```

**Comment by jpambrun** [comment]
It currently returns either Int16 or Uint16 based on whether the codestream is signed or not. It could easily be modified to return Uint8 to preserve memory when 16 bit are not required, but the main use case was medical images with high dynamic range.

**Comment by NicolasRannou** [comment]
Great! Thanks! Memory doesn't really matter to me, I just wanted to know which type of data to expect from it!

(also I have a questions about rgba support, not sure if there is a place to talk about it, if I should just open another issue, etc. to know if it is on the roadmap, if it is possible at all, etc. (I do not know much about data compression) )

Thanks

**Comment by jpambrun** [comment]
RGB/RGBA are definitely possible and should already work. However, it was not thoroughly tested after the original decoder was adapted to support 16 bits images. If you have any issue, let me know.

**Comment by NicolasRannou** [comment]
Thanks - I'll let you know. I'll test a j2k RBG dicom file when I have 5mn :)
